/**
 * STARTER QUESTION SET — 100 questions for launch testing on the live site.
 *
 * Drafted with AI assistance from well-documented facts, each with a
 * Wikipedia source. They have NOT been through Fastora's editorial
 * verification: they are tagged `starter-set` and `needs-review`, and
 * `verified_at` is left empty. Review them in Admin → Questions (edit or
 * archive any you disagree with) and replace them with the verified bank.
 *
 * Format: [category, difficulty, question, [correct, wrong, wrong, wrong],
 * explanation, country scope, Wikipedia article]. The SQL generator rotates
 * the correct answer's letter; options are shuffled again when issued.
 *
 * Generate the SQL with: npm run content:sql
 */
export type StarterQuestion = [
  category: string,
  difficulty: 'easy' | 'medium' | 'hard',
  text: string,
  options: [correct: string, string, string, string],
  explanation: string,
  scope: string[],
  wiki: string,
];

export const STARTER_QUESTIONS: StarterQuestion[] = [
  // ------------------------------------------------------------- history (11)
  ['history', 'easy', 'The ruined stone city of Great Zimbabwe is in which present-day country?', ['Zimbabwe', 'Mozambique', 'Zambia', 'Botswana'], 'Great Zimbabwe, built between the 11th and 15th centuries, lies near Masvingo in south-eastern Zimbabwe and gave the country its name.', ['ZW'], 'Great_Zimbabwe'],
  ['history', 'easy', 'Who was the first President of Kenya?', ['Jomo Kenyatta', 'Daniel arap Moi', 'Mwai Kibaki', 'Tom Mboya'], 'Jomo Kenyatta led Kenya to independence in 1963, first as Prime Minister and from 1964 as its first President.', ['KE'], 'Jomo_Kenyatta'],
  ['history', 'easy', 'Which country defeated an Italian army at the Battle of Adwa in 1896?', ['Ethiopia', 'Liberia', 'Egypt', 'Somalia'], 'Emperor Menelik II’s forces defeated Italy at Adwa in March 1896, securing Ethiopia’s independence.', ['ET'], 'Battle_of_Adwa'],
  ['history', 'medium', 'Mansa Musa, famous for his wealth and his 1324 pilgrimage to Mecca, ruled which empire?', ['The Mali Empire', 'The Songhai Empire', 'The Ghana Empire', 'The Kanem-Bornu Empire'], 'Mansa Musa ruled the Mali Empire in the early 14th century; his lavish pilgrimage made Mali famous across the Mediterranean world.', ['ML', 'WEST'], 'Mansa_Musa'],
  ['history', 'medium', 'Who was the first Prime Minister of the independent Democratic Republic of the Congo in 1960?', ['Patrice Lumumba', 'Joseph Kasa-Vubu', 'Mobutu Sese Seko', 'Moïse Tshombe'], 'Patrice Lumumba became Prime Minister at independence in June 1960; Joseph Kasa-Vubu was the first President.', ['CD'], 'Patrice_Lumumba'],
  ['history', 'medium', 'In which year was the Organisation of African Unity (OAU) founded?', ['1963', '1957', '1975', '1945'], 'The OAU was founded in Addis Ababa on 25 May 1963. It was replaced by the African Union in 2002.', ['AFRICA'], 'Organisation_of_African_Unity'],
  ['history', 'medium', 'Which city was the capital of the Asante (Ashanti) Empire?', ['Kumasi', 'Accra', 'Tamale', 'Cape Coast'], 'Kumasi, in present-day Ghana, was the capital of the Asante Empire and remains the seat of the Asantehene.', ['GH'], 'Ashanti_Empire'],
  ['history', 'hard', 'The Zulu victory over British forces at Isandlwana in 1879 came during the reign of which king?', ['Cetshwayo', 'Shaka', 'Dingane', 'Dinuzulu'], 'Cetshwayo kaMpande was king of the Zulu during the Anglo-Zulu War of 1879, which opened with the Zulu victory at Isandlwana.', ['ZA'], 'Battle_of_Isandlwana'],
  ['history', 'hard', 'The ancient Kingdom of Kush, whose kings ruled Egypt as its 25th Dynasty, was centred in which present-day country?', ['Sudan', 'Ethiopia', 'Libya', 'Chad'], 'Kush was based along the Nile in present-day Sudan, with capitals at Kerma, Napata and Meroë.', ['SD'], 'Kingdom_of_Kush'],
  ['history', 'hard', 'Which 17th-century queen of Ndongo and Matamba resisted Portuguese expansion in present-day Angola?', ['Queen Nzinga', 'Queen Amina', 'Yaa Asantewaa', 'Queen Makeda'], 'Nzinga Mbande ruled Ndongo and Matamba and fought Portuguese colonial expansion for decades.', ['AO'], 'Nzinga_of_Ndongo_and_Matamba'],
  ['history', 'hard', 'The ancient Kingdom of Aksum, which minted its own coins, was in present-day Ethiopia and which other country?', ['Eritrea', 'Somalia', 'Sudan', 'Djibouti'], 'Aksum, a major trading power from around the 1st century AD, covered what is now Eritrea and northern Ethiopia.', ['ET', 'ER'], 'Kingdom_of_Aksum'],

  // ----------------------------------------------------------- geography (12)
  ['geography', 'easy', 'What is the capital city of Nigeria?', ['Abuja', 'Lagos', 'Kano', 'Ibadan'], 'Abuja replaced Lagos as Nigeria’s capital in 1991. Lagos remains the largest city.', ['NG'], 'Abuja'],
  ['geography', 'easy', 'What is the capital city of Egypt?', ['Cairo', 'Alexandria', 'Giza', 'Luxor'], 'Cairo, on the Nile, is Egypt’s capital and one of the largest cities in Africa.', ['EG'], 'Cairo'],
  ['geography', 'easy', 'Which is the largest country in Africa by area?', ['Algeria', 'DR Congo', 'Sudan', 'Libya'], 'Algeria, at about 2.38 million km², has been Africa’s largest country since South Sudan separated from Sudan in 2011.', ['DZ'], 'Algeria'],
  ['geography', 'easy', 'Victoria Falls lies on the border between Zambia and which country?', ['Zimbabwe', 'Botswana', 'Namibia', 'Mozambique'], 'Victoria Falls, on the Zambezi River, sits on the border of Zambia and Zimbabwe. Its local name is Mosi-oa-Tunya.', ['ZM', 'ZW'], 'Victoria_Falls'],
  ['geography', 'medium', 'Lake Victoria is shared by Uganda, Kenya and which other country?', ['Tanzania', 'Rwanda', 'Burundi', 'Ethiopia'], 'Lake Victoria, Africa’s largest lake by area, is divided between Tanzania, Uganda and Kenya.', ['TZ', 'UG', 'KE'], 'Lake_Victoria'],
  ['geography', 'medium', 'What is the capital city of Senegal?', ['Dakar', 'Saint-Louis', 'Thiès', 'Bamako'], 'Dakar, on the Cap-Vert peninsula, is Senegal’s capital. Bamako is the capital of Mali.', ['SN'], 'Dakar'],
  ['geography', 'medium', 'Which island country in the Indian Ocean has Victoria as its capital?', ['Seychelles', 'Mauritius', 'Comoros', 'Madagascar'], 'Seychelles is made up of 115 islands; its capital, Victoria, is on the island of Mahé.', ['SC'], 'Seychelles'],
  ['geography', 'medium', 'The Atlas Mountains stretch across Morocco, Algeria and which other country?', ['Tunisia', 'Libya', 'Egypt', 'Mauritania'], 'The Atlas range runs for about 2,500 km through Morocco, Algeria and Tunisia.', ['MA', 'DZ', 'TN'], 'Atlas_Mountains'],
  ['geography', 'medium', 'Which country is completely surrounded by South Africa?', ['Lesotho', 'Eswatini', 'Botswana', 'Namibia'], 'Lesotho is an enclave entirely surrounded by South Africa. Eswatini also borders Mozambique.', ['LS'], 'Lesotho'],
  ['geography', 'hard', 'What is the capital city of Burkina Faso?', ['Ouagadougou', 'Bobo-Dioulasso', 'Niamey', 'Bamako'], 'Ouagadougou is Burkina Faso’s capital; Bobo-Dioulasso is its second city. Niamey is the capital of Niger.', ['BF'], 'Ouagadougou'],
  ['geography', 'hard', 'In Tanzania, Lake Malawi is known by which other name?', ['Lake Nyasa', 'Lake Kivu', 'Lake Turkana', 'Lake Chad'], 'Lake Malawi is called Lake Nyasa in Tanzania and Lago Niassa in Mozambique.', ['MW', 'TZ', 'MZ'], 'Lake_Malawi'],
  ['geography', 'hard', 'The Okavango Delta, an inland delta whose waters never reach the sea, is in which country?', ['Botswana', 'Namibia', 'Angola', 'Zambia'], 'The Okavango River rises in Angola and spreads into a vast inland delta in north-western Botswana.', ['BW'], 'Okavango_Delta'],

  // ------------------------------------------------------------- culture (11)
  ['culture', 'easy', 'Injera, a spongy sourdough flatbread, is a staple food in which country?', ['Ethiopia', 'Nigeria', 'Morocco', 'Senegal'], 'Injera, usually made from teff flour, is central to meals in Ethiopia and Eritrea.', ['ET', 'ER'], 'Injera'],
  ['culture', 'easy', 'The Maasai people live mainly in Kenya and which other country?', ['Tanzania', 'Uganda', 'Ethiopia', 'Somalia'], 'The Maasai are a Nilotic people of southern Kenya and northern Tanzania.', ['KE', 'TZ'], 'Maasai_people'],
  ['culture', 'easy', 'Tagine is both a slow-cooked stew and the clay pot it is cooked in. It is most associated with which country?', ['Morocco', 'Kenya', 'Ghana', 'Zambia'], 'The tagine, with its cone-shaped lid, is a signature of Moroccan and wider North African cooking.', ['MA'], 'Tajine'],
  ['culture', 'medium', 'Peri-peri (piri-piri) chilli sauce is most closely associated with the cooking of which country?', ['Mozambique', 'Morocco', 'Ethiopia', 'Ghana'], 'Peri-peri sauce developed in Mozambique from the African bird’s eye chilli and Portuguese cooking.', ['MZ'], 'Piri_piri'],
  ['culture', 'medium', 'The Argungu Fishing Festival is held in which country?', ['Nigeria', 'Ghana', 'Kenya', 'Egypt'], 'The Argungu Fishing Festival takes place in Kebbi State, north-western Nigeria.', ['NG'], 'Argungu_Fishing_Festival'],
  ['culture', 'medium', 'Bobotie, a spiced minced-meat dish baked with an egg topping, is associated with which country?', ['South Africa', 'Kenya', 'Ghana', 'Tunisia'], 'Bobotie is a South African dish with roots in Cape Malay cooking.', ['ZA'], 'Bobotie'],
  ['culture', 'medium', 'The Ndebele people, famous for brightly painted geometric house murals, live mainly in which country?', ['South Africa', 'Ethiopia', 'Nigeria', 'Morocco'], 'Southern Ndebele women are renowned for bold geometric wall paintings, especially in Mpumalanga, South Africa.', ['ZA'], 'Southern_Ndebele_people'],
  ['culture', 'medium', 'The Himba people, who coat their skin and hair with red ochre paste (otjize), live mainly in which country?', ['Namibia', 'Kenya', 'Mali', 'Ghana'], 'The Himba live mainly in the Kunene region of northern Namibia, with smaller communities in Angola.', ['NA'], 'Himba_people'],
  ['culture', 'hard', 'The Gerewol, a courtship festival where young men compete in beauty contests, is held by which people?', ['The Wodaabe', 'The Maasai', 'The Zulu', 'The Tuareg'], 'The Wodaabe, a Fulani pastoralist group of Niger and Chad, hold the Gerewol at the end of the rainy season.', ['NE', 'TD'], 'Wodaabe'],
  ['culture', 'hard', 'The Dogon people, known for cliffside villages on the Bandiagara Escarpment, live in which country?', ['Mali', 'Niger', 'Chad', 'Mauritania'], 'The Dogon live in central Mali; the Cliff of Bandiagara is a UNESCO World Heritage Site.', ['ML'], 'Dogon_people'],
  ['culture', 'hard', 'Which country made the Vodun (Voodoo) festival a national holiday every 10 January?', ['Benin', 'Togo', 'Ghana', 'Cameroon'], 'Benin celebrates Fête du Vodoun on 10 January, with major events in Ouidah. Vodun originated in this region.', ['BJ'], 'West_African_Vodun'],

  // ----------------------------------------------------------- languages (11)
  ['languages', 'easy', 'Which language is the most widely spoken first language in South Africa?', ['isiZulu', 'Afrikaans', 'English', 'Sesotho'], 'isiZulu is the first language of about a quarter of South Africans, more than any other language.', ['ZA'], 'Zulu_language'],
  ['languages', 'easy', 'Hausa is widely spoken in northern Nigeria and which other country?', ['Niger', 'Kenya', 'Angola', 'Egypt'], 'Hausa is a major language of northern Nigeria and southern Niger, and a lingua franca across much of West Africa.', ['NG', 'NE'], 'Hausa_language'],
  ['languages', 'easy', 'Arabic is the main official language of which of these countries?', ['Egypt', 'Kenya', 'Ghana', 'Zambia'], 'Arabic is Egypt’s official language; Egyptian Arabic is the most widely spoken variety of Arabic.', ['EG'], 'Egyptian_Arabic'],
  ['languages', 'medium', 'Which language, descended from Dutch, developed in South Africa?', ['Afrikaans', 'Sesotho', 'Setswana', 'isiXhosa'], 'Afrikaans grew out of the Dutch spoken in the Cape Colony and is one of South Africa’s official languages.', ['ZA', 'NA'], 'Afrikaans'],
  ['languages', 'medium', 'Wolof is the most widely spoken language in which country?', ['Senegal', 'Mali', 'Guinea', 'Cameroon'], 'Wolof is spoken by most Senegalese, as a first or second language, and also in The Gambia.', ['SN'], 'Wolof_language'],
  ['languages', 'medium', 'Which of these languages is written in the Ge’ez (Ethiopic) script?', ['Amharic', 'Somali', 'Hausa', 'Kiswahili'], 'Amharic uses the Ge’ez script, also called Ethiopic or Fidel. Somali, Hausa and Kiswahili are written in the Latin alphabet.', ['ET'], 'Ge%CA%BDez_script'],
  ['languages', 'medium', 'isiXhosa is well known for which distinctive kind of sound?', ['Click consonants', 'Nasal vowels only', 'Silent letters', 'Whistled speech'], 'isiXhosa has a large set of click consonants, written with the letters c, q and x.', ['ZA'], 'Xhosa_language'],
  ['languages', 'medium', 'Kiswahili, isiZulu, Shona and Kikuyu all belong to which large group of languages?', ['Bantu languages', 'Afroasiatic languages', 'Nilo-Saharan languages', 'Khoisan languages'], 'They are Bantu languages, a branch of the Niger–Congo family spoken across central, eastern and southern Africa.', ['AFRICA'], 'Bantu_languages'],
  ['languages', 'hard', 'Malagasy, the national language of Madagascar, is most closely related to languages from which region?', ['Borneo in Southeast Asia', 'West Africa', 'The Arabian Peninsula', 'Southern Europe'], 'Malagasy is an Austronesian language; its closest relatives are the Barito languages of southern Borneo.', ['MG'], 'Malagasy_language'],
  ['languages', 'hard', 'Lingala is a major lingua franca in DR Congo and which other country?', ['Republic of the Congo', 'Gabon', 'Angola', 'Cameroon'], 'Lingala is widely spoken in Kinshasa and western DR Congo and in Brazzaville, Republic of the Congo, and is popular in music.', ['CD', 'CG'], 'Lingala'],
  ['languages', 'hard', 'Chichewa (Nyanja) is the national language of which country?', ['Malawi', 'Botswana', 'Uganda', 'Lesotho'], 'Chichewa is Malawi’s national language and is also widely spoken in Zambia and Mozambique.', ['MW'], 'Chewa_language'],

  // ---------------------------------------------------------------- arts (11)
  ['arts', 'easy', 'Nollywood is the film industry of which country?', ['Nigeria', 'Ghana', 'Kenya', 'Egypt'], 'Nollywood, Nigeria’s film industry, is one of the largest in the world by number of films made.', ['NG'], 'Cinema_of_Nigeria'],
  ['arts', 'easy', 'Burna Boy and Wizkid are stars of which music genre?', ['Afrobeats', 'Gqom', 'Raï', 'Mbalax'], 'Afrobeats, a popular style from Nigeria and Ghana, made artists like Burna Boy and Wizkid global stars.', ['NG'], 'Afrobeats'],
  ['arts', 'easy', 'Amapiano music originated in which country?', ['South Africa', 'Nigeria', 'Kenya', 'Ghana'], 'Amapiano emerged in South Africa’s townships, especially around Gauteng, in the mid-2010s.', ['ZA'], 'Amapiano'],
  ['arts', 'medium', 'Which Senegalese singer recorded “7 Seconds” with Neneh Cherry?', ['Youssou N’Dour', 'Baaba Maal', 'Salif Keita', 'Akon'], 'Youssou N’Dour and Neneh Cherry released “7 Seconds” in 1994; it became an international hit.', ['SN'], '7_Seconds_(Youssou_N%27Dour_song)'],
  ['arts', 'medium', 'Who was the first African to win the Nobel Prize in Literature, in 1986?', ['Wole Soyinka', 'Chinua Achebe', 'Ben Okri', 'Ngũgĩ wa Thiong’o'], 'The Nigerian playwright and poet Wole Soyinka won the Nobel Prize in Literature in 1986.', ['NG'], 'Wole_Soyinka'],
  ['arts', 'medium', 'Ngũgĩ wa Thiong’o, author of “Weep Not, Child”, was from which country?', ['Kenya', 'Uganda', 'Tanzania', 'Nigeria'], 'Ngũgĩ wa Thiong’o was a Kenyan novelist who later championed writing in Gĩkũyũ.', ['KE'], 'Ng%C5%A9g%C4%A9_wa_Thiong%CA%BCo'],
  ['arts', 'medium', 'Highlife music originated in which country?', ['Ghana', 'Kenya', 'Egypt', 'South Africa'], 'Highlife began in Ghana in the early 20th century, blending local rhythms with Western instruments.', ['GH'], 'Highlife'],
  ['arts', 'hard', 'Which Egyptian singer was known as “Kawkab al-Sharq”, the Star of the East?', ['Umm Kulthum', 'Fairuz', 'Warda', 'Dalida'], 'Umm Kulthum was one of the Arab world’s most celebrated singers from the 1920s to the 1970s.', ['EG'], 'Umm_Kulthum'],
  ['arts', 'hard', 'Which Egyptian author won the Nobel Prize in Literature in 1988?', ['Naguib Mahfouz', 'Taha Hussein', 'Nawal El Saadawi', 'Alaa Al Aswany'], 'Naguib Mahfouz, author of the Cairo Trilogy, was the first Arabic-language writer to win the Nobel Prize in Literature.', ['EG'], 'Naguib_Mahfouz'],
  ['arts', 'hard', 'The Benin Bronzes were made in the Kingdom of Benin, which is in which present-day country?', ['Nigeria', 'Benin', 'Togo', 'Ghana'], 'The Kingdom of Benin was centred on Benin City in southern Nigeria. It is not the modern Republic of Benin.', ['NG'], 'Benin_Bronzes'],
  ['arts', 'hard', 'Which novel by Chimamanda Ngozi Adichie is set during the Nigerian Civil War?', ['Half of a Yellow Sun', 'Americanah', 'Purple Hibiscus', 'The Famished Road'], '“Half of a Yellow Sun” (2006) follows several characters through the Biafran War. “The Famished Road” is by Ben Okri.', ['NG'], 'Half_of_a_Yellow_Sun'],

  // -------------------------------------------------------------- sports (11)
  ['sports', 'easy', 'Mohamed Salah plays international football for which country?', ['Egypt', 'Morocco', 'Tunisia', 'Algeria'], 'Mohamed Salah is Egypt’s star forward and one of Africa’s best-known footballers.', ['EG'], 'Mohamed_Salah'],
  ['sports', 'easy', 'In 2022, which country became the first African team to reach a FIFA World Cup semi-final?', ['Morocco', 'Senegal', 'Cameroon', 'Ghana'], 'Morocco reached the semi-finals in Qatar in 2022, beating Spain and Portugal on the way.', ['MA'], 'Morocco_national_football_team'],
  ['sports', 'easy', 'Marathon great Eliud Kipchoge is from which country?', ['Kenya', 'Ethiopia', 'Uganda', 'Tanzania'], 'Eliud Kipchoge, a two-time Olympic marathon champion, is from Kenya.', ['KE'], 'Eliud_Kipchoge'],
  ['sports', 'easy', 'Which country’s national rugby team is nicknamed the Springboks?', ['South Africa', 'Namibia', 'Zimbabwe', 'Kenya'], 'The Springboks are South Africa’s national rugby union team and multiple Rugby World Cup winners.', ['ZA'], 'South_Africa_national_rugby_union_team'],
  ['sports', 'medium', 'Which country won the 2023 Africa Cup of Nations, played in early 2024?', ['Côte d’Ivoire', 'Nigeria', 'Senegal', 'Egypt'], 'Host nation Côte d’Ivoire beat Nigeria 2–1 in the final in Abidjan in February 2024.', ['CI'], '2023_Africa_Cup_of_Nations'],
  ['sports', 'medium', 'Which Ethiopian runner won the 1960 Olympic marathon running barefoot?', ['Abebe Bikila', 'Haile Gebrselassie', 'Kenenisa Bekele', 'Miruts Yifter'], 'Abebe Bikila won the Rome 1960 marathon barefoot, becoming Ethiopia’s first Olympic champion.', ['ET'], 'Abebe_Bikila'],
  ['sports', 'medium', 'Which country has won the most Africa Cup of Nations titles?', ['Egypt', 'Cameroon', 'Ghana', 'Nigeria'], 'Egypt has won the Africa Cup of Nations seven times, more than any other country.', ['EG'], 'Africa_Cup_of_Nations'],
  ['sports', 'medium', 'George Weah, the only African to win the Ballon d’Or, later became president of which country?', ['Liberia', 'Sierra Leone', 'Ghana', 'Côte d’Ivoire'], 'George Weah won the Ballon d’Or in 1995 and served as President of Liberia from 2018 to 2024.', ['LR'], 'George_Weah'],
  ['sports', 'hard', 'Who is the all-time top scorer in Africa Cup of Nations history?', ['Samuel Eto’o', 'Roger Milla', 'Didier Drogba', 'Laurent Pokou'], 'Cameroon’s Samuel Eto’o scored 18 goals at the Africa Cup of Nations, the tournament record.', ['CM'], 'Samuel_Eto%27o'],
  ['sports', 'hard', 'Who captained South Africa to victory at the 1995 Rugby World Cup on home soil?', ['Francois Pienaar', 'Siya Kolisi', 'John Smit', 'Joost van der Westhuizen'], 'Francois Pienaar received the trophy from President Nelson Mandela at Ellis Park in Johannesburg.', ['ZA'], '1995_Rugby_World_Cup_final'],
  ['sports', 'hard', 'Which Kenyan runner set the men’s 800 m world record of 1:40.91 at the 2012 Olympics?', ['David Rudisha', 'Wilson Kipketer', 'Paul Tergat', 'Kipchoge Keino'], 'David Rudisha ran 1:40.91 to win the London 2012 Olympic 800 m final, the first run under 1:41.', ['KE'], 'David_Rudisha'],

  // ------------------------------------------------------------- science (11)
  ['science', 'easy', 'Which is the fastest land animal, found on Africa’s savannahs?', ['The cheetah', 'The lion', 'The leopard', 'The Thomson’s gazelle'], 'Cheetahs can sprint at around 100 km/h over short distances.', ['AFRICA'], 'Cheetah'],
  ['science', 'easy', 'The “Big Five” are the lion, leopard, elephant, buffalo and which other animal?', ['The rhinoceros', 'The giraffe', 'The hippopotamus', 'The zebra'], 'The term “Big Five” first came from hunting; it now names the five animals that safari-goers most want to see.', ['AFRICA'], 'Big_five_game'],
  ['science', 'easy', 'Lemurs are native to which island country?', ['Madagascar', 'Mauritius', 'Cabo Verde', 'São Tomé and Príncipe'], 'Lemurs evolved in isolation on Madagascar, home to over 100 lemur species and subspecies.', ['MG'], 'Lemur'],
  ['science', 'medium', 'Which South African surgeon performed the world’s first human heart transplant in 1967?', ['Christiaan Barnard', 'Denton Cooley', 'Michael DeBakey', 'Norman Shumway'], 'Christiaan Barnard led the first human-to-human heart transplant at Groote Schuur Hospital, Cape Town, in December 1967.', ['ZA'], 'Christiaan_Barnard'],
  ['science', 'medium', 'Which Kenyan environmentalist founded the Green Belt Movement and won the 2004 Nobel Peace Prize?', ['Wangari Maathai', 'Graça Machel', 'Ellen Johnson Sirleaf', 'Leymah Gbowee'], 'Wangari Maathai’s Green Belt Movement has planted tens of millions of trees. She was the first African woman to win the Nobel Peace Prize.', ['KE'], 'Wangari_Maathai'],
  ['science', 'medium', 'The fossil skeleton “Lucy” (Australopithecus afarensis) was discovered in which country?', ['Ethiopia', 'Kenya', 'Tanzania', 'South Africa'], 'Lucy was found at Hadar in Ethiopia’s Afar region in 1974 and is about 3.2 million years old.', ['ET'], 'Lucy_(Australopithecus)'],
  ['science', 'medium', 'Mountain gorillas live in the Virunga Mountains, shared by Rwanda, Uganda and which other country?', ['DR Congo', 'Kenya', 'Burundi', 'Tanzania'], 'The Virunga volcanoes straddle Rwanda, Uganda and DR Congo; mountain gorillas also live in Uganda’s Bwindi forest.', ['RW', 'UG', 'CD'], 'Mountain_gorilla'],
  ['science', 'hard', 'Which African river is the deepest recorded river in the world?', ['The Congo River', 'The Nile', 'The Niger River', 'The Zambezi'], 'Parts of the lower Congo River are over 220 m deep, the greatest depth recorded for any river.', ['CD', 'CG'], 'Congo_River'],
  ['science', 'hard', 'The Cradle of Humankind, a World Heritage Site rich in early human fossils, is in which country?', ['South Africa', 'Ethiopia', 'Kenya', 'Tanzania'], 'The Cradle of Humankind, near Johannesburg, includes the Sterkfontein caves, where “Mrs Ples” and “Little Foot” were found.', ['ZA'], 'Cradle_of_Humankind'],
  ['science', 'hard', 'The okapi, a forest relative of the giraffe, lives in the wild only in which country?', ['DR Congo', 'Gabon', 'Cameroon', 'Uganda'], 'The okapi is endemic to the rainforests of DR Congo, where it is a national symbol.', ['CD'], 'Okapi'],
  ['science', 'hard', 'The Square Kilometre Array radio telescope is being built in Australia and which African country?', ['South Africa', 'Kenya', 'Egypt', 'Namibia'], 'The SKA’s mid-frequency dishes are being built in South Africa’s Karoo, building on the MeerKAT telescope.', ['ZA'], 'Square_Kilometre_Array'],

  // ---------------------------------------------------------- innovation (11)
  ['innovation', 'easy', 'M-Pesa, the mobile money service launched in 2007, started in which country?', ['Kenya', 'Nigeria', 'South Africa', 'Ghana'], 'Safaricom launched M-Pesa in Kenya in 2007, letting people send and receive money by phone.', ['KE'], 'M-Pesa'],
  ['innovation', 'easy', 'Which South African-born entrepreneur founded SpaceX?', ['Elon Musk', 'Mark Shuttleworth', 'Patrice Motsepe', 'Strive Masiyiwa'], 'Elon Musk was born in Pretoria in 1971 and founded SpaceX in 2002.', ['ZA'], 'Elon_Musk'],
  ['innovation', 'easy', 'Which country’s tech scene is nicknamed “Silicon Savannah”?', ['Kenya', 'Egypt', 'Morocco', 'Angola'], '“Silicon Savannah” refers to Kenya’s tech sector, centred on Nairobi.', ['KE'], 'Silicon_Savannah'],
  ['innovation', 'medium', 'The online marketplace Jumia was founded in 2012 in which country?', ['Nigeria', 'Kenya', 'Egypt', 'Senegal'], 'Jumia launched in Lagos, Nigeria, in 2012 and expanded across Africa.', ['NG'], 'Jumia'],
  ['innovation', 'medium', 'Which Lagos-founded payments company was bought by Stripe in 2020?', ['Paystack', 'Flutterwave', 'Interswitch', 'Chipper Cash'], 'Stripe acquired Paystack in 2020, one of the largest deals in African tech at the time.', ['NG'], 'Paystack'],
  ['innovation', 'medium', 'The Grand Ethiopian Renaissance Dam is built on which river?', ['The Blue Nile', 'The White Nile', 'The Omo', 'The Awash'], 'The dam on the Blue Nile in western Ethiopia is the largest hydroelectric plant in Africa.', ['ET'], 'Grand_Ethiopian_Renaissance_Dam'],
  ['innovation', 'medium', 'Aliko Dangote, for many years Africa’s richest person, built his fortune mainly in which industry?', ['Cement', 'Mobile phones', 'Oil exploration', 'Banking'], 'Dangote Cement is Africa’s largest cement producer. The Dangote Group has since built a major oil refinery near Lagos.', ['NG'], 'Aliko_Dangote'],
  ['innovation', 'hard', 'The Inga dams, at one of the world’s greatest potential hydropower sites, are in which country?', ['DR Congo', 'Angola', 'Zambia', 'Cameroon'], 'Inga I and Inga II stand on the lower Congo River in DR Congo, near the Inga Falls.', ['CD'], 'Inga_dams'],
  ['innovation', 'hard', 'Which Sudanese-born telecoms entrepreneur founded Celtel and a prize for African leadership?', ['Mo Ibrahim', 'Aliko Dangote', 'Strive Masiyiwa', 'Tony Elumelu'], 'Mo Ibrahim founded Celtel in 1998 and set up the Mo Ibrahim Foundation, which awards the Ibrahim Prize.', ['SD'], 'Mo_Ibrahim'],
  ['innovation', 'hard', 'Strive Masiyiwa founded which telecoms group, which began in Zimbabwe?', ['Econet', 'MTN', 'Safaricom', 'Airtel'], 'Strive Masiyiwa founded Econet Wireless, which won a long legal battle to launch mobile service in Zimbabwe in the 1990s.', ['ZW'], 'Strive_Masiyiwa'],
  ['innovation', 'hard', 'The Noor Ouarzazate complex, one of the world’s largest concentrated solar power plants, is in which country?', ['Morocco', 'Egypt', 'Algeria', 'South Africa'], 'Noor Ouarzazate, on the edge of the Sahara in Morocco, uses mirrors to concentrate sunlight to generate electricity.', ['MA'], 'Ouarzazate_Solar_Power_Station'],

  // ------------------------------------------------------------- society (11)
  ['society', 'easy', 'What is the currency of Nigeria?', ['The naira', 'The cedi', 'The rand', 'The shilling'], 'The naira, introduced in 1973, is Nigeria’s currency.', ['NG'], 'Nigerian_naira'],
  ['society', 'easy', 'What is the currency of South Africa?', ['The rand', 'The kwacha', 'The pula', 'The naira'], 'The rand takes its name from the Witwatersrand, the ridge where Johannesburg’s gold was found.', ['ZA'], 'South_African_rand'],
  ['society', 'easy', 'Which African country has the largest population?', ['Nigeria', 'Ethiopia', 'Egypt', 'DR Congo'], 'Nigeria is Africa’s most populous country, with over 200 million people.', ['NG'], 'Demographics_of_Nigeria'],
  ['society', 'medium', 'Ellen Johnson Sirleaf became Africa’s first elected female head of state in which country?', ['Liberia', 'Malawi', 'Ghana', 'Sierra Leone'], 'Ellen Johnson Sirleaf was President of Liberia from 2006 to 2018 and shared the 2011 Nobel Peace Prize.', ['LR'], 'Ellen_Johnson_Sirleaf'],
  ['society', 'medium', 'How many member states does the African Union have?', ['55', '54', '50', '48'], 'All 55 internationally recognised states of the continent, including the Sahrawi Republic, are AU members.', ['AFRICA'], 'Member_states_of_the_African_Union'],
  ['society', 'medium', 'Africa Day, marking the founding of the OAU, is celebrated on which date?', ['25 May', '1 July', '12 October', '9 August'], 'Africa Day is held every year on 25 May, the date the Organisation of African Unity was founded in 1963.', ['AFRICA'], 'Africa_Day'],
  ['society', 'medium', 'The cedi is the currency of which country?', ['Ghana', 'Kenya', 'Zambia', 'Gambia'], 'The Ghanaian cedi takes its name from the Akan word for cowry shells, once used as money.', ['GH'], 'Ghanaian_cedi'],
  ['society', 'hard', 'The East African Community has its headquarters in which city?', ['Arusha', 'Nairobi', 'Kampala', 'Kigali'], 'The East African Community secretariat is in Arusha, Tanzania.', ['TZ', 'EAST'], 'East_African_Community'],
  ['society', 'hard', 'The secretariat of the African Continental Free Trade Area (AfCFTA) is in which city?', ['Accra', 'Addis Ababa', 'Kigali', 'Nairobi'], 'The AfCFTA secretariat opened in Accra, Ghana, in 2020.', ['GH', 'AFRICA'], 'African_Continental_Free_Trade_Area'],
  ['society', 'hard', 'Which country’s parliament has had the world’s highest share of women members?', ['Rwanda', 'South Africa', 'Senegal', 'Namibia'], 'Women have held a majority of seats in Rwanda’s lower house since 2008, the highest share in the world.', ['RW'], 'Women_in_Rwanda'],
  ['society', 'hard', 'In which South African town does the Pan-African Parliament meet?', ['Midrand', 'Pretoria', 'Cape Town', 'Durban'], 'The Pan-African Parliament, the African Union’s legislative body, sits in Midrand, Gauteng, South Africa.', ['ZA', 'AFRICA'], 'Pan-African_Parliament'],
];
