/**
 * Builds db/seed/starter_questions_100.sql from db/content/starter-questions.ts.
 * Run: npm run content:sql
 *
 * The SQL is meant to be pasted into the Supabase SQL editor (or run with
 * psql). It creates the categories if missing and inserts every question as
 * approved and live, with deterministic ids, so running it twice changes
 * nothing.
 */
import { createHash } from 'node:crypto';
import { writeFileSync, mkdirSync } from 'node:fs';
import { STARTER_QUESTIONS } from '../db/content/starter-questions';
import { DEFAULT_CATEGORIES } from '../src/lib/shared/categories';
import { normaliseForHash, OPTION_LABELS, QuestionInputSchema } from '../src/lib/shared/question-input';

export const STARTER_TAGS = ['starter-set', 'needs-review'];

/** Deterministic UUID (version 5 layout) from a name. */
function uuidFor(name: string): string {
  const h = createHash('sha1').update('fastora-starter:' + name).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-${((parseInt(h.slice(16, 18), 16) & 0x3f) | 0x80).toString(16)}${h.slice(18, 20)}-${h.slice(20, 32)}`;
}
const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (xs: string[]) => `array[${xs.map(lit).join(', ')}]::text[]`;

export function buildStarterSql(): { sql: string; count: number } {
  const cats = new Set<string>(DEFAULT_CATEGORIES.map((c) => c.id));
  const hashes = new Set<string>();
  const questions: string[] = [];
  const versions: string[] = [];
  const options: string[] = [];
  const keys: string[] = [];
  const stats: string[] = [];
  STARTER_QUESTIONS.forEach(([category, difficulty, text, opts, explanation, scope, wiki], i) => {
    if (!cats.has(category)) throw new Error(`Unknown category ${category} (#${i + 1})`);
    // Rotate the correct answer through A–D.
    const correctIdx = i % 4;
    const ordered = [...opts.slice(1)];
    ordered.splice(correctIdx, 0, opts[0]);
    const input = QuestionInputSchema.parse({
      text,
      options: Object.fromEntries(OPTION_LABELS.map((l, k) => [l, ordered[k]])),
      correct: OPTION_LABELS[correctIdx],
      explanation,
      categoryId: category,
      countryScope: scope,
      difficulty,
      tags: STARTER_TAGS,
      sources: [{ title: `Wikipedia: ${decodeURIComponent(wiki).replace(/_/g, ' ')}`, url: `https://en.wikipedia.org/wiki/${wiki}` }],
    });
    const hash = createHash('sha256').update(normaliseForHash(input.text)).digest('hex');
    if (hashes.has(hash)) throw new Error(`Duplicate question #${i + 1}: ${text}`);
    hashes.add(hash);
    const qid = uuidFor('q:' + hash);
    const vid = uuidFor('v:' + hash);
    questions.push(`(${lit(qid)}, 'approved', ${lit(vid)}, ${lit(vid)}, false)`);
    versions.push(
      `(${lit(vid)}, ${lit(qid)}, 1, 'approved', ${lit(input.text)}, ${lit(input.explanation)}, ${lit(input.categoryId)}, ${arr(input.countryScope)}, ` +
        `${lit(input.difficulty)}, 'all', ${arr(input.tags)}, 'en', ${lit(JSON.stringify(input.sources))}::jsonb, ${lit(hash)}, now())`,
    );
    OPTION_LABELS.forEach((l) => options.push(`(${lit(uuidFor(`o:${hash}:${l}`))}, ${lit(vid)}, '${l}', ${lit(input.options[l])})`));
    keys.push(`(${lit(vid)}, ${lit(uuidFor(`o:${hash}:${input.correct}`))})`);
    stats.push(`(${lit(vid)})`);
  });
  const sep = ',\n  ';
  const sql = `-- Fastora: starter question set (${STARTER_QUESTIONS.length} questions)
-- Generated by scripts/build-starter-sql.ts from db/content/starter-questions.ts.
-- Do not edit by hand; edit the source file and run: npm run content:sql
--
-- Drafted with AI assistance and NOT yet editorially verified: every question is
-- tagged 'starter-set' and 'needs-review'. Review them in Admin → Questions.
-- Safe to run more than once (fixed ids, "on conflict do nothing").
-- Run in Supabase: Dashboard → SQL Editor → New query → paste → Run.

begin;

insert into public.categories (id, name, description, sort_order) values
  ${DEFAULT_CATEGORIES.map((c, i) => `(${lit(c.id)}, ${lit(c.name)}, ${lit(c.description)}, ${i})`).join(sep)}
on conflict (id) do nothing;

insert into public.questions (id, status, live_version_id, latest_version_id, is_fixture) values
  ${questions.join(sep)}
on conflict (id) do nothing;

insert into public.question_versions
  (id, question_id, version, state, text, explanation, category_id, country_scope, difficulty, age_rating, tags, language, sources, content_hash, published_at)
values
  ${versions.join(sep)}
on conflict (id) do nothing;

insert into public.question_options (id, version_id, label, text) values
  ${options.join(sep)}
on conflict (id) do nothing;

insert into private.answer_keys (version_id, correct_option_id) values
  ${keys.join(sep)}
on conflict (version_id) do nothing;

insert into public.question_stats (version_id) values
  ${stats.join(sep)}
on conflict (version_id) do nothing;

commit;

-- Check: approved starter questions per category and difficulty.
select v.category_id, v.difficulty, count(*) as questions
  from public.questions q join public.question_versions v on v.id = q.live_version_id
 where q.status = 'approved' and 'starter-set' = any(v.tags)
 group by 1, 2 order by 1, 2;
`;
  return { sql, count: STARTER_QUESTIONS.length };
}

if (process.argv[1]?.endsWith('build-starter-sql.ts')) {
  const { sql, count } = buildStarterSql();
  mkdirSync('db/seed', { recursive: true });
  writeFileSync('db/seed/starter_questions_100.sql', sql);
  console.log(`Wrote db/seed/starter_questions_100.sql (${count} questions).`);
}
