/**
 * Builds db/seed/supabase_full_setup.sql: one file that sets up an EMPTY
 * Supabase database for Fastora in a single run (schema, access control,
 * Realtime policy, default settings, the 100 starter questions, and Ghost
 * opponents switched on).
 * Run: npm run content:sql (also rebuilds the starter question file)
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { DEFAULT_FLAGS, DEFAULT_RULES } from '../src/lib/game/rules';
import { buildStarterSql } from './build-starter-sql';

const strip = (sql: string) => sql.replace(/^begin;$/m, '').replace(/^commit;$/m, '');

export function buildSetupSql(): string {
  const dir = 'db/migrations';
  const files = readdirSync(dir).filter((f) => f.endsWith('.sql')).sort();
  const migrations = files.map((f) => `-- ===== ${f} =====\n${readFileSync(path.join(dir, f), 'utf8').trim()}\n`).join('\n');
  const realtime = readFileSync('db/supabase/realtime_policies.sql', 'utf8')
    .split('\n')
    .filter((l) => !l.startsWith('--'))
    .join('\n')
    .trim()
    .replace(/;\s*$/, '');
  const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
  // The starter file ends with a check query; keep only its inserts here.
  const starter = strip(buildStarterSql().sql).split('-- Check: approved starter questions')[0].trim();
  return `-- Fastora: COMPLETE SETUP for an EMPTY Supabase database (project "fastora").
-- Generated by scripts/build-setup-sql.ts. Do not edit by hand; run: npm run content:sql
--
-- Run ONCE in Supabase: Dashboard > SQL Editor > New query > paste > Run.
-- It creates every table, the access rules (RLS), the Realtime policy for
-- live matches, the default game settings, the ${files.length} migration records,
-- the 100 starter questions, and switches on Ghost opponents.
--
-- SAFETY: it refuses to run if the database already has tables in the public
-- schema (for example a different app's project, or a second run). Nothing is
-- changed in that case. Everything runs in one transaction: all or nothing.

begin;

do $guard$
begin
  if exists (select 1 from pg_tables where schemaname = 'public') then
    raise exception 'This database already has tables in the public schema (% found). Fastora setup needs an EMPTY project. Check you are in the "fastora" project (its URL contains tsfhuyxvznpzbmwcswkq). If Fastora is already set up, run only starter_questions_100.sql and enable_ghost_opponents.sql.',
      (select count(*) from pg_tables where schemaname = 'public');
  end if;
end
$guard$;

${migrations}
-- ===== Migration records (so "npm run db:migrate" skips these files) =====
create table if not exists private.app_migrations (name text primary key, applied_at timestamptz not null default now());
alter table private.app_migrations enable row level security;
insert into private.app_migrations (name) values
  ${files.map((f) => `(${lit(f)})`).join(',\n  ')}
on conflict (name) do nothing;

-- ===== Realtime authorisation for live-match channels (Supabase only) =====
do $rt$
begin
  if to_regclass('realtime.messages') is not null
     and not exists (select 1 from pg_policies where schemaname = 'realtime' and tablename = 'messages'
                     and policyname = 'match participants can receive match pings') then
    execute ${lit(realtime)};
  end if;
end
$rt$;

-- ===== Default game settings (v1), then v2 with Ghost opponents on =====
insert into public.game_config (version, rules, flags, note)
values (1, ${lit(JSON.stringify(DEFAULT_RULES))}::jsonb, ${lit(JSON.stringify(DEFAULT_FLAGS))}::jsonb, 'Proposed defaults')
on conflict (version) do nothing;
insert into public.game_config (version, rules, flags, note)
select version + 1, rules, flags || '{"ghostOpponents": true}'::jsonb, 'Ghost opponents switched on (setup SQL)'
  from public.game_config order by version desc limit 1;

-- ===== 100 starter questions =====
${starter}

commit;

-- ===== Checks =====
select (select count(*) from pg_tables where schemaname = 'public') as public_tables,
       (select count(*) from public.questions where status = 'approved') as approved_questions,
       (select flags ->> 'ghostOpponents' from public.game_config order by version desc limit 1) as ghost_opponents_on;
`;
}

if (process.argv[1]?.endsWith('build-setup-sql.ts')) {
  writeFileSync('db/seed/supabase_full_setup.sql', buildSetupSql());
  console.log('Wrote db/seed/supabase_full_setup.sql');
}
